import type { TranscriptSegment as LegacyTranscriptSegment, VideoInfo } from '@/lib/types';

export type PlatformKey = 'youtube' | 'bilibili';

export interface VideoRef {
  platform: PlatformKey;
  canonicalUrl: string;
  platformVideoId: string;
  platformPartId?: string | null;
  raw?: Record<string, unknown>;
}

export interface VideoMetadata {
  platform: PlatformKey;
  platformVideoId: string;
  platformPartId?: string | null;
  canonicalUrl: string;
  title: string;
  author?: string;
  thumbnail?: string;
  duration?: number | null;
  description?: string;
  tags?: string[];
  language?: string;
  availableLanguages?: string[];
  raw?: unknown;
}

export type TranscriptSource = 'manual' | 'auto' | 'ai' | 'unknown';

export interface NormalizedTranscriptSegment extends LegacyTranscriptSegment {
  id: string;
  end: number;
  source?: TranscriptSource;
  language?: string;
  confidence?: number;
}

export interface TranscriptQuality {
  segmentCount: number;
  durationCoverage?: number;
  isMonotonic: boolean;
  emptySegmentRatio: number;
  warnings: string[];
}

export interface TranscriptOptions {
  preferredLanguage?: string;
  allowAutoGenerated?: boolean;
  expectedDuration?: number | null;
}

export interface TranscriptResult {
  segments: NormalizedTranscriptSegment[];
  language?: string;
  availableLanguages?: string[];
  source: TranscriptSource;
  quality: TranscriptQuality;
  warnings: string[];
  raw?: unknown;
}

export interface PlayerEmbedConfig {
  kind: 'iframe' | 'api';
  src: string;
  canProgrammaticSeek: boolean;
}

export interface VideoPlatformAdapter {
  platform: PlatformKey;
  canHandle(url: string): boolean;
  parseUrl(url: string): Promise<VideoRef>;
  fetchMetadata(ref: VideoRef): Promise<VideoMetadata>;
  fetchTranscript(ref: VideoRef, options?: TranscriptOptions): Promise<TranscriptResult>;
  getEmbedConfig(ref: VideoRef): PlayerEmbedConfig;
}

export function videoInfoToMetadata(info: VideoInfo, canonicalUrl: string): VideoMetadata {
  return {
    platform: 'youtube',
    platformVideoId: info.videoId,
    canonicalUrl,
    title: info.title,
    author: info.author,
    thumbnail: info.thumbnail,
    duration: info.duration,
    description: info.description,
    tags: info.tags,
    language: info.language,
    availableLanguages: info.availableLanguages,
    raw: info,
  };
}
